# This file was generated by Nuitka

# Stubs included by default
from typing_extensions import Self
import time
import docker
import os
from test.TestUtils import TestUtils
import unittest
import requests
import sys

class TestDockerHttpdApache:
    @classmethod
    def setUpClass(cls, ) -> typing.Any: ...
    @classmethod
    def tearDownClass(cls, ) -> typing.Any: ...
    @classmethod
    def wait_for_container_to_be_running(cls, timeout: typing.Any) -> typing.Any: ...
    def test_container_running(self: Self) -> typing.Any: ...
    def test_apache_installed(self: Self) -> typing.Any: ...
    def test_apache_service_running(self: Self) -> typing.Any: ...
    def test_apache_access(self: Self) -> typing.Any: ...
    def test_apache_default_page(self: Self) -> typing.Any: ...
def run_all_tests() -> typing.Any:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import unittest
import docker
import time
import requests
import os
import ntpath
import test
import test.TestUtils